export const countryList = [
	{ label: 'Thailand', value: 'Thailand' },
	{ label: 'United States', value: 'United States' },
	{ label: 'Canada', value: 'Canada' },
	{ label: 'United Kingdom', value: 'United Kingdom' },
	{ label: 'Australia', value: 'Australia' },
	{ label: 'Germany', value: 'Germany' },
	{ label: 'France', value: 'France' },
	{ label: 'Italy', value: 'Italy' },
	{ label: 'Spain', value: 'Spain' },
	{ label: 'Japan', value: 'Japan' },
	{ label: 'China', value: 'China' },
	{ label: 'India', value: 'India' },
	{ label: 'Brazil', value: 'Brazil' },
	{ label: 'Mexico', value: 'Mexico' },
	{ label: 'Russia', value: 'Russia' },
	{ label: 'South Korea', value: 'South Korea' },
	{ label: 'South Africa', value: 'South Africa' },
	{ label: 'New Zealand', value: 'New Zealand' },
	{ label: 'Argentina', value: 'Argentina' },
	{ label: 'Chile', value: 'Chile' },
	{ label: 'Colombia', value: 'Colombia' },
	{ label: 'Peru', value: 'Peru' },
	{ label: 'Venezuela', value: 'Venezuela' },
	{ label: 'Egypt', value: 'Egypt' },
	{ label: 'Nigeria', value: 'Nigeria' },
	{ label: 'Kenya', value: 'Kenya' },
	{ label: 'Turkey', value: 'Turkey' },
	{ label: 'Saudi Arabia', value: 'Saudi Arabia' },
	{ label: 'United Arab Emirates', value: 'United Arab Emirates' },
	{ label: 'Israel', value: 'Israel' },
	{ label: 'Pakistan', value: 'Pakistan' },
	{ label: 'Bangladesh', value: 'Bangladesh' },
	{ label: 'Indonesia', value: 'Indonesia' },
	{ label: 'Malaysia', value: 'Malaysia' },
	{ label: 'Singapore', value: 'Singapore' },
	{ label: 'Philippines', value: 'Philippines' },
	{ label: 'Vietnam', value: 'Vietnam' },
	{ label: 'Thailand', value: 'Thailand' },
	{ label: 'Myanmar', value: 'Myanmar' },
	{ label: 'Sri Lanka', value: 'Sri Lanka' },
	{ label: 'Nepal', value: 'Nepal' },
	{ label: 'Bhutan', value: 'Bhutan' },
	{ label: 'Maldives', value: 'Maldives' },
	{ label: 'Afghanistan', value: 'Afghanistan' },
	{ label: 'Iran', value: 'Iran' },
	{ label: 'Iraq', value: 'Iraq' },
	{ label: 'Syria', value: 'Syria' },
	{ label: 'Jordan', value: 'Jordan' },
	{ label: 'Lebanon', value: 'Lebanon' },
	{ label: 'Kuwait', value: 'Kuwait' },
	{ label: 'Qatar', value: 'Qatar' },
	{ label: 'Bahrain', value: 'Bahrain' },
	{ label: 'Oman', value: 'Oman' },
].sort((a, b) => a.label.localeCompare(b.label));
